<?xml version="1.0" encoding="UTF-8"?>
<!-- December 5, 2012 -->
<wsdl:definitions
   targetNamespace="http://www.telefonica.com/wsdl/UNICA/SOAP/common/v2/faults"
   xmlns:tns="http://www.telefonica.com/wsdl/UNICA/SOAP/common/v2/faults" 
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:uct="http://www.telefonica.com/schemas/UNICA/SOAP/common/v2">

   <wsdl:types>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"			
			elementFormDefault="qualified">	
      	
     <xsd:import namespace="http://www.telefonica.com/schemas/UNICA/SOAP/common/v2" schemaLocation="UNICA_API_SOAP_common_types_v2_1.xsd"/>
            
      </xsd:schema>
	
	</wsdl:types>

   <wsdl:message name="ServerException">
      <wsdl:part name="ServerException" element="uct:serverException"/>
   </wsdl:message>

   <wsdl:message name="ClientException">
      <wsdl:part name="ClientException" element="uct:clientException"/>
   </wsdl:message>
   
</wsdl:definitions>
