ALTER TRIGGER CWPC_TAXVERSION_REMOVE DISABLE;
DELETE CWPC_TAX_V;
ALTER TRIGGER CWPC_TAXVERSION_REMOVE ENABLE;

ALTER TRIGGER CWPC_TAXMODELVERSION_REMOVE DISABLE;
DELETE CWPC_TAXMODEL_V;
ALTER TRIGGER CWPC_TAXMODELVERSION_REMOVE ENABLE;

ALTER TRIGGER CWPC_TAXMODELITEM_REMOVE DISABLE;
DELETE CWPC_TAXMODELITEM;
ALTER TRIGGER CWPC_TAXMODELITEM_REMOVE ENABLE;

ALTER TRIGGER CWPC_TAXMODEL_REMOVE DISABLE;
DELETE CWPC_TAXMODEL;
ALTER TRIGGER CWPC_TAXMODEL_REMOVE ENABLE;

ALTER TRIGGER CWPC_SYSTEMIDENTIFIER_REMOVE DISABLE;
DELETE CWPC_SYSTEMIDENTIFIER;
ALTER TRIGGER CWPC_SYSTEMIDENTIFIER_REMOVE ENABLE;

ALTER TRIGGER CWPC_RULEPARAMETERS_REMOVE DISABLE;
DELETE CWPC_RULEPARAMETERS;
ALTER TRIGGER CWPC_RULEPARAMETERS_REMOVE ENABLE;

DELETE CWPC_PROJECTCOMMAND;
DELETE CWPC_PROJECT;
DELETE CWPC_PERMISSION;
DELETE CWPC_ITEMTYPEPERMISSION;

ALTER TRIGGER CWPC_ITEMRULE_REMOVE DISABLE;
DELETE CWPC_ITEMRULE_V;
ALTER TRIGGER CWPC_ITEMRULE_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMRELATION_REMOVE DISABLE;
DELETE CWPC_ITEMRELATION_V;
ALTER TRIGGER CWPC_ITEMRELATION_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMLABEL_REMOVE DISABLE;
DELETE CWPC_ITEMLABEL_V;
ALTER TRIGGER CWPC_ITEMLABEL_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMIMAGE_REMOVE DISABLE;
DELETE CWPC_ITEMIMAGE_V;
ALTER TRIGGER CWPC_ITEMIMAGE_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMHIERARCHY_REMOVE DISABLE;
DELETE CWPC_ITEMHIERARCHY;
ALTER TRIGGER CWPC_ITEMHIERARCHY_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMCHARGE_REMOVE DISABLE;
DELETE CWPC_ITEMCHARGE_V;
ALTER TRIGGER CWPC_ITEMCHARGE_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMATTRIBUTE_REMOVE DISABLE;
DELETE CWPC_ITEMATTRIBUTE_V;
ALTER TRIGGER CWPC_ITEMATTRIBUTE_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMATTACHMENT_REMOVE DISABLE;
DELETE CWPC_ITEMATTACHMENT_V;
ALTER TRIGGER CWPC_ITEMATTACHMENT_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEM_REMOVE DISABLE;
DELETE CWPC_ITEM;
ALTER TRIGGER CWPC_ITEM_REMOVE ENABLE;

ALTER TRIGGER CWPC_INFOTABLE_REMOVE DISABLE;
DELETE CWPC_INFOTABLE;
ALTER TRIGGER CWPC_INFOTABLE_REMOVE ENABLE;

ALTER TRIGGER CWPC_INFOMODELATTRIBUTE_REMOVE DISABLE;
DELETE CWPC_INFOMODELATTRIBUTE;
ALTER TRIGGER CWPC_INFOMODELATTRIBUTE_REMOVE ENABLE;

ALTER TRIGGER CWPC_GROUPTARGET_REMOVE DISABLE;
DELETE CWPC_GROUPTARGET;
ALTER TRIGGER CWPC_GROUPTARGET_REMOVE ENABLE;

DELETE CWPC_DELETEDOBJECTRECORD;

ALTER TRIGGER CWPC_CONTEXTATTRIBUTE_REMOVE DISABLE;
DELETE CWPC_CONTEXTATTRIBUTE;
ALTER TRIGGER CWPC_CONTEXTATTRIBUTE_REMOVE ENABLE;

ALTER TRIGGER CWPC_CHARGETYPEVERSION_REMOVE DISABLE;
DELETE CWPC_CHARGETYPE_V;
ALTER TRIGGER CWPC_CHARGETYPEVERSION_REMOVE ENABLE;

ALTER TRIGGER CWPC_CATALOGRULEVERSION_REMOVE DISABLE;
DELETE CWPC_CATALOGRULE_V;
ALTER TRIGGER CWPC_CATALOGRULEVERSION_REMOVE ENABLE;

ALTER TRIGGER CWPC_CATALOGRULE_REMOVE DISABLE;
DELETE CWPC_CATALOGRULE;
ALTER TRIGGER CWPC_CATALOGRULE_REMOVE ENABLE;

DELETE CWPC_CATALOGDOMAIN;
DELETE CWPC_CATALOGCONFIGURATION;
DELETE CWPC_BASKETITEMRELATION;
DELETE CWPC_BASKETITEMLEAVES;
DELETE CWPC_BASKETITEMCHARGE;
DELETE CWPC_BASKETITEM;
DELETE CWPC_BASKET;


ALTER TRIGGER CWPC_ASSOCIATIONTYPE_REMOVE DISABLE;
DELETE CWPC_ASSOCIATIONTYPE;
ALTER TRIGGER CWPC_ASSOCIATIONTYPE_REMOVE ENABLE;

ALTER TRIGGER CWPC_ASSOCIATNATTRVALUE_REMOVE DISABLE;
DELETE CWPC_ASSOCIATIONATTRVALUE;
ALTER TRIGGER CWPC_ASSOCIATNATTRVALUE_REMOVE ENABLE;

ALTER TRIGGER CWPC_TAX_REMOVE DISABLE;
ALTER TRIGGER CWPC_TAXVERSION_REMOVE DISABLE;
DELETE CWPC_TAX CASCADE;
ALTER TRIGGER CWPC_TAX_REMOVE ENABLE;
ALTER TRIGGER CWPC_TAXVERSION_REMOVE ENABLE;

ALTER TRIGGER CWPC_RESTRICTION_V_REMOVE DISABLE;
ALTER TRIGGER CWPC_ASSOCIATNATTRVALUE_REMOVE DISABLE;
DELETE CWPC_RESTRICTION_V CASCADE;
ALTER TRIGGER CWPC_RESTRICTION_V_REMOVE ENABLE;
ALTER TRIGGER CWPC_ASSOCIATNATTRVALUE_REMOVE ENABLE;

ALTER TRIGGER CWPC_ITEMGROUP_REMOVE DISABLE;
ALTER TRIGGER CWPC_GROUPTARGET_REMOVE DISABLE;
DELETE CWPC_ITEMGROUP_V CASCADE;
ALTER TRIGGER CWPC_ITEMGROUP_REMOVE ENABLE;
ALTER TRIGGER CWPC_GROUPTARGET_REMOVE ENABLE;

ALTER TRIGGER CWPC_INFOMODEL_REMOVE DISABLE;
ALTER TRIGGER CWPC_INFOMODELATTRIBUTE_REMOVE DISABLE;
DELETE CWPC_INFOMODEL CASCADE;
ALTER TRIGGER CWPC_INFOMODEL_REMOVE ENABLE;
ALTER TRIGGER CWPC_INFOMODELATTRIBUTE_REMOVE ENABLE;

ALTER TRIGGER CWPC_CONTEXT_REMOVE DISABLE;
ALTER TRIGGER CWPC_CONTEXTATTRIBUTE_REMOVE DISABLE;
DELETE CWPC_CONTEXT CASCADE;
ALTER TRIGGER CWPC_CONTEXT_REMOVE ENABLE;
ALTER TRIGGER CWPC_CONTEXTATTRIBUTE_REMOVE ENABLE;

ALTER TRIGGER CWPC_CHARGETYPE_REMOVE DISABLE;
ALTER TRIGGER CWPC_CHARGETYPEVERSION_REMOVE DISABLE;
DELETE CWPC_CHARGETYPE CASCADE;
ALTER TRIGGER CWPC_CHARGETYPE_REMOVE ENABLE;
ALTER TRIGGER CWPC_CHARGETYPEVERSION_REMOVE ENABLE;

ALTER TRIGGER CWPC_CATALOGHIERARCHY_REMOVE DISABLE;
ALTER TRIGGER CWPC_ITEMHIERARCHY_REMOVE DISABLE;
DELETE CWPC_CATALOGHIERARCHY CASCADE;
ALTER TRIGGER CWPC_CATALOGHIERARCHY_REMOVE ENABLE;
ALTER TRIGGER CWPC_ITEMHIERARCHY_REMOVE ENABLE;

ALTER TRIGGER CWPC_ASSOCIATNTYPATTR_REMOVE DISABLE;
ALTER TRIGGER CWPC_ASSOCIATNATTRVALUE_REMOVE DISABLE;
DELETE CWPC_ASSOCIATIONTYPEATTR CASCADE;
ALTER TRIGGER CWPC_ASSOCIATNTYPATTR_REMOVE ENABLE;
ALTER TRIGGER CWPC_ASSOCIATNATTRVALUE_REMOVE ENABLE;

ALTER TRIGGER CWPC_ATTRIBUTE_REMOVE DISABLE;
DELETE CWPC_ATTRIBUTE;
ALTER TRIGGER CWPC_ATTRIBUTE_REMOVE ENABLE;
COMMIT;
