--UPDATE CWPC_PROJECT SET STATUS = 'DEF';


-- DEFivate all objects in catalog
UPDATE CWPC_ATTRIBUTE SET STATUS = 'DEF';
UPDATE CWPC_ITEM SET STATUS = 'DEF';
UPDATE CWPC_ITEMATTRIBUTE_V SET STATUS = 'DEF';
UPDATE CWPC_CHARGETYPE_V SET STATUS = 'DEF';
UPDATE CWPC_RESTRICTION_V SET STATUS = 'DEF';
UPDATE CWPC_TAX_V SET STATUS = 'DEF';
UPDATE CWPC_ITEMCHARGE_V SET STATUS = 'DEF';
UPDATE CWPC_ITEMRULE_V SET STATUS = 'DEF';
UPDATE CWPC_ITEMIMAGE_V SET STATUS = 'DEF';
UPDATE CWPC_ITEMATTACHMENT_V SET STATUS = 'DEF';
UPDATE CWPC_CATALOGHIERARCHY SET STATUS = 'DEF';
UPDATE CWPC_ITEMHIERARCHY SET STATUS = 'DEF';
UPDATE CWPC_ASSOCIATIONTYPE SET STATUS = 'DEF';
UPDATE CWPC_ITEMRELATION_V SET STATUS = 'DEF';
UPDATE CWPC_ITEMLABEL_V SET STATUS = 'DEF';
UPDATE CWPC_ITEMGROUP_V SET STATUS = 'DEF';
UPDATE CWPC_INFOMODEF SET STATUS = 'DEF';
UPDATE CWPC_CATALOGRULE_V SET STATUS = 'DEF';
UPDATE CWPC_TAXMODEF_V SET STATUS = 'DEF';
UPDATE CWPC_INFOTABLE SET STATUS = 'DEF';
UPDATE CWPC_CONTEXT SET STATUS = 'DEF';
commit;

--UPDATE CWPC_PROJECT SET STATUS = 'ACT';


-- ACTivate all objects in catalog
UPDATE CWPC_ATTRIBUTE SET STATUS = 'ACT';
UPDATE CWPC_ITEM SET STATUS = 'ACT';
UPDATE CWPC_ITEMATTRIBUTE_V SET STATUS = 'ACT';
UPDATE CWPC_CHARGETYPE_V SET STATUS = 'ACT';
UPDATE CWPC_RESTRICTION_V SET STATUS = 'ACT';
UPDATE CWPC_TAX_V SET STATUS = 'ACT';
UPDATE CWPC_ITEMCHARGE_V SET STATUS = 'ACT';
UPDATE CWPC_ITEMRULE_V SET STATUS = 'ACT';
UPDATE CWPC_ITEMIMAGE_V SET STATUS = 'ACT';
UPDATE CWPC_ITEMATTACHMENT_V SET STATUS = 'ACT';
UPDATE CWPC_CATALOGHIERARCHY SET STATUS = 'ACT';
UPDATE CWPC_ITEMHIERARCHY SET STATUS = 'ACT';
UPDATE CWPC_ASSOCIATIONTYPE SET STATUS = 'ACT';
UPDATE CWPC_ITEMRELATION_V SET STATUS = 'ACT';
UPDATE CWPC_ITEMLABEL_V SET STATUS = 'ACT';
UPDATE CWPC_ITEMGROUP_V SET STATUS = 'ACT';
UPDATE CWPC_INFOMODEL SET STATUS = 'ACT';
UPDATE CWPC_CATALOGRULE_V SET STATUS = 'ACT';
UPDATE CWPC_TAXMODEL_V SET STATUS = 'ACT';
UPDATE CWPC_INFOTABLE SET STATUS = 'ACT';
UPDATE CWPC_CONTEXT SET STATUS = 'ACT';
commit;