UPDATE CWPC_ITEMATTRIBUTE_V SET STATUS='DEF' WHERE ITEMATTRVERSIONID IN (SELECT CATALOGOBJECTID FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_itemAttribute' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAA'));
UPDATE CWPC_ITEMRELATION_V SET STATUS='DEF' WHERE ITEMCODE IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_item' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAA'));
UPDATE CWPC_ITEMLABEL_V SET STATUS='DEF' WHERE ITEMCODE IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_item' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAA'));
UPDATE CWPC_ITEM SET STATUS='DEF' WHERE ITEMCODE IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_item' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAA'));
UPDATE CWPC_PROJECT SET STATUS='DEF' WHERE PROJECTCODE='NGAA';

COMMIT;
