DELETE CWPC_ITEMATTRIBUTE_V WHERE ITEMATTRVERSIONID IN (SELECT CATALOGOBJECTID FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_itemAttribute' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration'));
DELETE CWPC_ITEMRELATION_V WHERE ITEMCODE IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_item' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration'));
DELETE CWPC_ITEMRELATION_V WHERE ITEMRELATIONTARGET IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_item' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration'));
DELETE CWPC_ITEMLABEL_V WHERE ITEMCODE IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_item' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration'));
DELETE CWPC_ITEM WHERE ITEMCODE IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_item' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration'));
DELETE CWPC_ATTRIBUTE WHERE ATTRIBUTECODE IN (SELECT CATALOGOBJECTCODE FROM CWPC_PROJECTCOMMAND WHERE OBJECTTYPE='cwt_pc:cwt_attribute' AND PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration'));
DELETE CWPC_PROJECTCOMMAND WHERE PROJECTID=(SELECT PROJECTID FROM CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration');
DELETE CWPC_PROJECT WHERE PROJECTCODE='NGAAConfiguration';
COMMIT;