delete from ERRORES_ACT;
truncate table ERRORES_ACT;

Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','BD');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','BN');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','BU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','CH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','EX');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','LE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','MC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','MI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1','Subscriber does not exist','MT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','D2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','D3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','D5');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','D6');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','D7');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','D8');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','D9');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','E2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','E3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','E5');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','E6');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','E7');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','E8');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','E9');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','H1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','K1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','M3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'30','Subscriber in incorrect state.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','AB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','AE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','AY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','BB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','BE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','BY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','CN');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','CP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','CT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','EA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','LF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'301','Rejected operation: OPGE inconsistency. Subscriber does not exist.','ZA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','AB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','AE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','AY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','BB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','BE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','BY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','CN');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'302','Rejected operation: SDP inconsistency. Subscriber does not exist.','LF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3002','Generic Error in Resignation correction or Migration.','MI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3011','Error in the HLR, in Confirmation of high.','PA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3012','Service not allowed for the subscriber lifecycle.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3013','Credit limit and date of billing: Function not allowed for the cycle of subscriber','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3014','Cycle not configured for that service','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3017','The subscriber is already deactivated.','BD');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3017','The subscriber is already deactivated.','BN');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3017','The subscriber is already deactivated.','BU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3017','The subscriber is already deactivated.','EX');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3018','Generic Error, in Confirmation low.','BN');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3018','Generic Error, in Confirmation low.','BU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3018','Generic Error, in Confirmation low.','EX');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3020','Generic error in Change Confirmation GSM HLR.','CH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3021','Service is not configured for the subscriber cycle.','CH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3022','Service not allowed for the cycle of subscriber.','CH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3023','Failed to send the script to the HLR','CT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3028','Error while sending the script to SDP','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3028','Error while sending the script to SDP','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3030','Service not allowed for the subscriber lifecycle','CT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3032','Failed to retrieve parameter: Msisdn','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3032','Failed to retrieve parameter: Msisdn','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3033','Amount of recharge can not compensate for the sum of all SOS recharges','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3033','Amount of recharge can not compensate for the sum of all SOS recharges','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','AE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','AY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','BE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','BY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','CN');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','CP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','CT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','LF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3034','Wrong subscriber status','ZA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3035','Service not allowed for the subscriber lifecycle','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3036','Cycle not configured for that service','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3037','General failure of the process.','MC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3038','Service is not configured for the subscriber cycle.','MC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3039','Service not allowed for the cycle of subscriber.','MC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3040','Error accessing the database.','MC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3041','Arrive wrong parameters in the request.','MC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3042','Shared Memory Error.','MT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3043','Error sending script.','MT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3044','Configuration error, service not configured for the subscriber lifecycle.','MT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3051','The cycle of the subscriber does not allow the operation.','LE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3051','The cycle of the subscriber does not allow the operation.','LF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3052','Operation not processed (error running the script).','AE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3052','Operation not processed (error running the script).','BE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3052','Operation not processed (error running the script).','LE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3052','Operation not processed (error running the script).','LF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3053','Generic Error, in confirming the modification of control spending limit.','LE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3057','Service not allowed for the subscriber lifecycle.','PO');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3058','Lifecycle not configured for the service.','PO');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3062','Generic error reported in update UCC notification','LF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3063','Subscriber belonging to Nested Account','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3063','Subscriber belonging to Nested Account','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3064','The maximum length of time in the current status has been exceeded','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3064','The maximum length of time in the current status has been exceeded','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'270001','Not valid code of bag','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300028','Upper Limit Excedeed','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300028','Upper Limit Excedeed','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300028','Upper Limit Excedeed','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300031','Defined maximum time since last top up undefined top up origin codes associated','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300031','Defined maximum time since last top up undefined top up origin codes associated','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300032','Number of OPGE top up origin codes exceeds the maximum supported by application','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300032','Number of OPGE top up origin codes exceeds the maximum supported by application','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300033','Error while retrieving parameter. Top up amount','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300033','Error while retrieving parameter. Top up amount','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300034','Error while retrieving parameter. Top up origin','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300034','Error while retrieving parameter. Top up origin','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300035','Error while retrieving parameter. Top up validity period','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300035','Error while retrieving parameter. Top up validity period','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300036','Error while retrieving parameter. Maximum period without penalty','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300036','Error while retrieving parameter. Maximum period without penalty','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300037','Error while retrieving parameter. Penalty cost','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300037','Error while retrieving parameter. Penalty cost','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300038','Pending SOS top up limit exceeded by the subscriber','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300038','Pending SOS top up limit exceeded by the subscriber','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300039','There are no top ups of the allowed OPGE top up origin code for the subscriber','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300039','There are no top ups of the allowed OPGE top up origin code for the subscriber','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300040','The maximum length of time since the last top up has been exceeded','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300040','The maximum length of time since the last top up has been exceeded','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300041','TCC: Error while retrieving the life cycle for the type of prepay','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300041','TCC: Error while retrieving the life cycle for the type of prepay','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300042','GOI: Error while retrieving the order script identifier','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300042','GOI: Error while retrieving the order script identifier','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300043','TTP: Error while retrieving the type of Prepay card','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300043','TTP: Error while retrieving the type of Prepay card','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300044','CCR: Error while retrieving the OPGE top up origin code per top up origin','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300044','CCR: Error while retrieving the OPGE top up origin code per top up origin','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300045','GUIÓN: The balance of the subscriber is greater than allowed','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300045','GUIÓN: The balance of the subscriber is greater than allowed','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300046','Error while retrieving parameter. Tax','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300046','Error while retrieving parameter. Tax','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300047','Not allowed the cancellation on replacement top-up.','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'300047','Not allowed the cancellation on replacement top-up.','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'320008','Insufficient balance.','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800068','Failed to create a dynamic list.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800069','Failed to insert into a dynamic list.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800070','Failed to insert into a dynamic list.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800071','Failed to retrieve parameter: number list.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800072','Failed to retrieve parameter: Initial List of frequently called numbers.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800073','Failed to retrieve parameter: List of frequently called numbers end.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800074','Failed to retrieve parameter: Item list.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800075','Failed to retrieve parameter: List item 2.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800076','Failed to retrieve parameter: S or N Enable / Disable List.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800077','Frequently dialed numbers equal start and end.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800078','List item larger than permitted.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800079','Event flag value of Enable / Disable list can only be S or N.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800080','Subscriber may not have cancellations.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800081','SDP: Code list nonexistent.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800082','SDP: full list.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800083','SDP: Item already exists.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','EF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','QF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','UF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'800084','SDP: Item not found.','XF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'900001','Subscriber not in the suitable state','MI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900039','Service not allowed for the subscriber lifecycle','AB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900039','Service not allowed for the subscriber lifecycle','BB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900062','Cycle not configured for that service','AB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900062','Cycle not configured for that service','BB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900072','SDP: Value forbidden for bolt ons.','AB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900072','SDP: Value forbidden for bolt ons.','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900072','SDP: Value forbidden for bolt ons.','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'1900078','SDP: Maximum number of renewals achieved.','RK');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200001','The tribe has expired','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200002','The subscriber is not actived in the tribe','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200003','The subscriber is already actived in the tribe','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200003','The subscriber is already actived in the tribe','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200006','The tribe is full','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200008','The tribe does not exist','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200008','The tribe does not exist','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200017','GOI: Failed to retrieve orders scripts identifier','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200019','Failed to retrieve parameter: Tribe number.','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200020','Failed to send the script to SDP','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200022','SDP: Operation not processed.','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200023','Subscriber does not exist.','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200027','Failed to retrieve parameter: Cost','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200031','SDP: Subscriber does not exist.','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200039','Error select BD','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200040','TCC: Error retrieving life-cycle for the type of plans','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200041','Failed to retrieve parameter: New Msisdn','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200042','Failed to retrieve parameter: Original Msisdn','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200043','Cycle not configured for that service.','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200043','Cycle not configured for that service.','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200043','Cycle not configured for that service.','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200044','Service not allowed for the subscriber lifecycle','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200044','Service not allowed for the subscriber lifecycle','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200044','Service not allowed for the subscriber lifecycle','TM');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200046','Error recovering parameter: Subtribe.','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2200046','Error recovering parameter: Subtribe.','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500017','SDP: Balance insufficient to perform the operation','AQ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500017','SDP: Balance insufficient to perform the operation','AY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500017','SDP: Balance insufficient to perform the operation','BY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500019','Failed to send the message to the SDP Central (script)','AY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500019','Failed to send the message to the SDP Central (script)','BY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500020','Failure to extract the arguments','AY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500020','Failure to extract the arguments','BY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500021','Error select BD','AY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2500021','Error select BD','BY');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700017','SDP: Format incorrectly of Extra Rating parameter','CT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700017','SDP: Format incorrectly of Extra Rating parameter','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700018','SDP: Service Provider Incorrect Parameter','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700019','SDP: Missing parameter Service Provider','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700020','Failed to retrieve parameter: SDP Profile','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700021','Failed to retrieve parameter: Tax Category','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700022','Failed to retrieve parameter: Supplementary Services Identifier','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700023','Failed to retrieve parameter: Supplementary Services Value','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700024','Failed to retrieve parameter: Credit Limit','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700025','Failed to retrieve parameter: Billing Date','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700026','Failed to retrieve parameter: CUIT Company','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700027','Failed to retrieve parameter: Client Code','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700028','IRM: Failed to retrieve centrals.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700029','DIR: Error retrieving machine','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700030','CON: Failed to retrieve language','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700031','Error select BD','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700032','Number of supplementary services received exceeds the maximum','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700033','TCC: Error retrieving life-cycle for the type of plans','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700034','Failed to retrieve parameter: Extra Rating Chain','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700035','Failed to retrieve parameter: Service Provider','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700036','Credit Limit or billing date not received and mandatory.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700037','Received credit limit is negative.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700038','CUIT Enterprise and Customer Code: Function not allowed for the subscriber cycle','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700039','Service Provider: Function not allowed for the cycle of subscriber','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700040','Extra Rating: Function not allowed for the cycle of subscriber','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700041','Cycle not configured for functionality: Credit Limit and Billing Date','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700042','Cycle not configured for functionality: CUIT and Customer Code','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700043','Cycle not configured for functionality: Service Provider','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700044','Cycle not configured for functionality: Extra Rating','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700045','SCRIPT: Cycle not configured for functionality: Send Category Tax','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700046','SCRIPT: Cycle not configured for functionality: Send HLR','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700047','SCRIPT: Cycle not configured for the feature: Send Technology','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700048','SCRIPT: Cycle not configured for functionality: Send IMSI','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700049','Failed to retrieve parameter: Msisdn','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700050','Failed to retrieve parameter: Cost','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700051','Failed to retrieve parameter: Destination State','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700052','SDP: Value of incorrect credit limit','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2700053','SDP: Incorrect Billing Date','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900001','Subscriber does not exist.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900002','Subscriber is blocked.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900003','Subscriber with incorrect state.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900004','Target incorrect State.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900005','SDP received does not exist.','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900006','Error updating to BD','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900007','The SDP received or stored in subscriber have not free numbers','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900008','The SDP received or stored in subscriber has not assigned numbers','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900009','The SDP received did not correspond with the technology of the subscriber','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900010','We do not allow SDP code received as a parameter','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'2900013','Supplementary service identifier invalid','DI');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000001','Mistake if the subscriber does not exist.','BJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000001','Mistake if the subscriber does not exist.','BZ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000001','Mistake if the subscriber does not exist.','EA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000002','Mistake The subscriber is already deactivated.','BJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000002','Mistake The subscriber is already deactivated.','BZ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000002','Mistake The subscriber is already deactivated.','EA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000005','Error acceding the Database.','BJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000005','Error acceding the Database.','BZ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3000005','Error acceding the Database.','EA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3600006','Do not allow the cancellation of base rates.','MT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700001','Recharge to compensate out of time, amount of penalty is not enough','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700001','Recharge to compensate out of time, amount of penalty is not enough','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700001','Recharge to compensate out of time, amount of penalty is not enough','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700002','The amount is not enough to offset the recharge SOS','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700002','The amount is not enough to offset the recharge SOS','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700002','The amount is not enough to offset the recharge SOS','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700005','The amount of recharge is not within the allowed range','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700005','The amount of recharge is not within the allowed range','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700005','The amount of recharge is not within the allowed range','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3700017','SDP: Balance insufficient to perform the operation','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800001','Failed to send the script to SDP','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800001','Failed to send the script to SDP','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800002','Subscriber does not exist','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800002','Subscriber does not exist','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800003','Subscriber to the wrong state','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800003','Subscriber to the wrong state','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800004','Cycle not configured for that service','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800004','Cycle not configured for that service','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800005','Failed to retrieve parameters: MSISDN','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800005','Failed to retrieve parameters: MSISDN','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800006','Failed to retrieve parameters: Cost','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800006','Failed to retrieve parameters: Cost','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800007','Failed to retrieve parameter: Type of promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800007','Failed to retrieve parameter: Type of promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800008','Failed to retrieve parameter: Bonus','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800008','Failed to retrieve parameter: Bonus','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800009','Failed to retrieve parameter: Promotion Start Date','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800009','Failed to retrieve parameter: Promotion Start Date','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800010','Failed to retrieve parameter: Promotion End Date','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800010','Failed to retrieve parameter: Promotion End Date','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800011','Failed to retrieve parameter: Period promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800011','Failed to retrieve parameter: Period promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800012','Failed to retrieve parameter: Value franchisee promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800012','Failed to retrieve parameter: Value franchisee promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800013','Failed to retrieve parameter: Flag of incremental promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800013','Failed to retrieve parameter: Flag of incremental promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800014','Failed to retrieve parameter: Charge Type','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800014','Failed to retrieve parameter: Charge Type','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800015','Failed to retrieve parameter: Tariff','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800015','Failed to retrieve parameter: Tariff','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800016','Failed to retrieve parameter: Number of Ranges','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800016','Failed to retrieve parameter: Number of Ranges','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800017','Failed to retrieve parameter: Year','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800017','Failed to retrieve parameter: Year','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800018','Failed to retrieve parameter: Month','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800018','Failed to retrieve parameter: Month','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800019','Failed to retrieve parameter: Day of the month','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800019','Failed to retrieve parameter: Day of the month','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800020','Failed to retrieve parameter: Day of the week','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800020','Failed to retrieve parameter: Day of the week','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800021','Failed to retrieve parameter: Hour','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800021','Failed to retrieve parameter: Hour','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800022','Failed to retrieve parameter: Length','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800022','Failed to retrieve parameter: Length','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800023','Failed to check if the promotion comes from a RASCA charge','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800023','Failed to check if the promotion comes from a RASCA charge','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800024','Promotion does not exist in poge_promociones','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800024','Promotion does not exist in poge_promociones','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800025','Invalid state for discharging a promotion without suspension','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800025','Invalid state for discharging a promotion without suspension','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800026','The cause of suspension of the subscriber does not apply to promotions','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800026','The cause of suspension of the subscriber does not apply to promotions','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800027','Promotion does not exist in poge_abopromociones','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800027','Promotion does not exist in poge_abopromociones','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800028','Error select BD','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800028','Error select BD','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800029','Service not allowed for the subscriber lifecycle','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800029','Service not allowed for the subscriber lifecycle','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800030','Under current operations are not allowed to charge','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800030','Under current operations are not allowed to charge','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800031','There is already a subscriber promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800031','There is already a subscriber promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800032','TCC: Failed to retrieve the life cycle for the type of prepaid','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800032','TCC: Failed to retrieve the life cycle for the type of prepaid','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800033','GOI: Failed to retrieve orders scripts identifier','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800033','GOI: Failed to retrieve orders scripts identifier','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800034','RUT: Failed to retrieve the routing for the generic interface','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800034','RUT: Failed to retrieve the routing for the generic interface','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800035','SCRIPT: Cycle not configured for functionality: Promotions with hours','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800035','SCRIPT: Cycle not configured for functionality: Promotions with hours','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800036','SCRIPT: Promotion does not exist in poge_abopromociones','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800037','SDP: subscriber does not exist','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800037','SDP: subscriber does not exist','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800038','SDP: Balance insufficient to perform the operation','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800038','SDP: Balance insufficient to perform the operation','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800039','SDP: nonexistent Promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800039','SDP: nonexistent Promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800040','SDP: Expired Promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800040','SDP: Expired Promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800041','SDP: Promotion already exists (after MAX_NUM_REINTENTOS_ALTA retry the script)','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800041','SDP: Promotion already exists (after MAX_NUM_REINTENTOS_ALTA retry the script)','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800042','SDP: Promotion undefined to user','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800043','SDP: Promotional general','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800043','SDP: Promotional general','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800044','SDP: Data missing promotion','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800044','SDP: Data missing promotion','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800045','SDP: Maximum number of promotions exceeded','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800045','SDP: Maximum number of promotions exceeded','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800046','SDP: charge mode not set','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800046','SDP: charge mode not set','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800047','SCRIPT: Subscriber does not exist','BP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'3800047','SCRIPT: Subscriber does not exist','PH');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000003','Subscriber in wrong state','AB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000003','Subscriber in wrong state','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000003','Subscriber in wrong state','BB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000003','Subscriber in wrong state','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000004','GOI: Failed to retrieve orders scripts identifier','BB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000008','SDP: subscriber does not exist','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000008','SDP: subscriber does not exist','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','AB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','AE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','AJ');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','AT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','BB');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','BE');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','BT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','CN');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','CP');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','CT');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','DS');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000009','SDP: Balance insufficient to perform the operation','RK');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000011','Service not allowed for the subscriber lifecycle','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000011','Service not allowed for the subscriber lifecycle','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000012','Non-configured cycle for this service','RA');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4000012','Non-configured cycle for this service','RC');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500001','Error to send the script to SDP','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500001','Error to send the script to SDP','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500001','Error to send the script to SDP','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500001','Error to send the script to SDP','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500002','Subscriber does not exist','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500002','Subscriber does not exist','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500002','Subscriber does not exist','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500002','Subscriber does not exist','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500003','Cycle not configured for functionality: Third Threshold','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500003','Cycle not configured for functionality: Third Threshold','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500003','Cycle not configured for functionality: Third Threshold','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500003','Cycle not configured for functionality: Third Threshold','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500004','Cycle not configured for functionality: Third Threshold','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500004','Cycle not configured for functionality: Third Threshold','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500004','Cycle not configured for functionality: Third Threshold','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500004','Cycle not configured for functionality: Third Threshold','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500005','Cycle not configured for functionality: Second Threshold','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500005','Cycle not configured for functionality: Second Threshold','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500005','Cycle not configured for functionality: Second Threshold','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500005','Cycle not configured for functionality: Second Threshold','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500006','Cycle is not configured for that service','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500006','Cycle is not configured for that service','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500006','Cycle is not configured for that service','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500006','Cycle is not configured for that service','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500007','Error to retrieve parameter: Balance Threshold','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500007','Error to retrieve parameter: Balance Threshold','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500007','Error to retrieve parameter: Balance Threshold','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500007','Error to retrieve parameter: Balance Threshold','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500008','Error when selecting in BD','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500008','Error when selecting in BD','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500008','Error when selecting in BD','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500008','Error when selecting in BD','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500009','Service not allowed for the subscriber life cycle','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500009','Service not allowed for the subscriber life cycle','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500009','Service not allowed for the subscriber life cycle','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500009','Service not allowed for the subscriber life cycle','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500010','Third Threshold: Function not allowed for the subscriber cycle','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500010','Third Threshold: Function not allowed for the subscriber cycle','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500010','Third Threshold: Function not allowed for the subscriber cycle','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500010','Third Threshold: Function not allowed for the subscriber cycle','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500011','Second Threshold: Function not allowed for the subscriber cycle','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500011','Second Threshold: Function not allowed for the subscriber cycle','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500011','Second Threshold: Function not allowed for the subscriber cycle','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500011','Second Threshold: Function not allowed for the subscriber cycle','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500012','GOI: Error to retrieve ID shell scripts','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500012','GOI: Error to retrieve ID shell scripts','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500012','GOI: Error to retrieve ID shell scripts','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500012','GOI: Error to retrieve ID shell scripts','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500013','TCC: Error to retrieve the life cycle for the type of prepaid','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500013','TCC: Error to retrieve the life cycle for the type of prepaid','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500013','TCC: Error to retrieve the life cycle for the type of prepaid','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500013','TCC: Error to retrieve the life cycle for the type of prepaid','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500014','SDP: Subscriber does not exist','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500014','SDP: Subscriber does not exist','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500014','SDP: Subscriber does not exist','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500014','SDP: Subscriber does not exist','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500015','SDP: Balance insufficient to perform the operation','EU');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500015','SDP: Balance insufficient to perform the operation','P1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500015','SDP: Balance insufficient to perform the operation','P2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'4500015','SDP: Balance insufficient to perform the operation','P3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','D2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','D3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','D5');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','D6');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','D7');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','D8');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','D9');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','E2');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','E3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','E5');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','E6');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','E7');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','E8');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','E9');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','H1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','HF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','IF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','JF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','K1');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','KF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','M3');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','NF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','SF');
Insert into ERRORES_ACT (CWDOCID,COD_ERROR,NVL,COD_ACTUACION) values (CWDOCSEQ.NEXTVAL,'99800008','Insufficient balance.','XF');

commit;