delete from ratingtreenodetypes;
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('AT',	'Air Time',	'ct',	'ATNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('CAT',	'Call Type',	'ct',	'CATNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('COT',	'Content type',	'ct',	'COTNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('D',	'Distance',	'ct',	'DNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('ECS',	'External Client Subtype',	'ct',	'');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('ECT',	'External Client Type',	'ct',	'');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('FNS',	'Frequent Numbers (SMS)',	'ntt',	'List');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('FNV',	'Frequent Numbers (Voice)',	'ntt',	'List');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('G',	'Generic',	'att',	'');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('HZ',	'Home Zone',	'ct',	'HZNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('LC',	'Location Cell',	'ct',	'LCNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('LD',	'Long Distance',	'ct',	'LDNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('MLD',	'Mandatory Long Distance',	'ct',	'MLDNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('OO',	'Onnet-Offnet',	'ct',	'OONodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('OOS',	'Onnet-Offnet SMS',	'ct',	'OOSNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('ORZ',	'Origin Roaming Zone',	'ct',	'ORZNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('OZT',	'Office Zone Type',	'ct',	'OZTNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('PSO',	'Presubscribed Operator',	'ntt',	'LongDistanceOperator');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('PTT',	'PTT',	'ct',	'PTTNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('PT',	'Public Telephone',	'ct',	'PTNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('QM',	'Query method',	'ct',	'QMNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('RP',	'Reverted Payment',	'ct',	'RPNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('RZ',	'Roaming Zone',	'ct',	'RZNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('S',	'Service',	'ct',	'SNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('SC',	'Service Center',	'ntt',	'DestinationType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('SP',	'Service Provider',	'ntt',	'ServiceProvider');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('SZ',	'Special Zone',	'ct',	'SZNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('T',	'Tribes',	'ntt',	'Tribe');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('TN',	'Type of Number',	'ntt',	'Ton');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('TNS',	'Type of Number (SMS)',	'ct',	'TNSNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('TP',	'Tariff Plan',	'ntt',	'TariffPlan ServiceTariffPlan');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('TPC',	'Third Party Charge',	'ct',	'TPCNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('TSD',	'TeleService Data',	'ct',	'TSDNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('TSV',	'TeleService Voice',	'ct',	'TSVNodeType');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('TT',	'Traffic Type',	'ct',	'FABDestFreeDestTrafficTypeCodeTa');
insert into ratingtreenodetypes(code,description,nodetype,nodetypevalue) values ('UT',	'Units type',	'ct',	'UTNodeType');
commit;