delete from mensapatrones;
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'abo_orig_ts','Abonado que realiza la transferencia de saldo','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'abonado','Número de abonado','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'cod_bolsa_caducada','Bolsa caducada','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_bolsa_caducada','Descripción de bolsa caducada','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_sbactuacion','Descripcion de la subactuacion','100');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_DD.MM.YYYY','Fecha de la recargas SOS en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_DD.MM.YYYYHHMM','Fecha de la recargas SOS en formato DD.MM.YYYY HH:MI','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_DDMMYYYY','Fecha de la recargas SOS en formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_DDMMYYYYHHMM','Fecha de la recargas SOS en formato DD/MM/YYYY HH:MI','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_MM.DD.YYYY','Fecha de la recargas SOS en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_MM.DD.YYYYHHMM','Fecha de la recargas SOS en formato MM.DD.YYYY HH:MI','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_MMDDYYYY','Fecha de la recargas SOS en formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_SOS_MMDDYYYYHHMM','Fecha de la recargas SOS en formato MM/DD/YYYY HH:MI','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_DD.MM.YYYY','fecha actual formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_DD.MM.YYYYHHMM','fecha actual formato DD.MM.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_DDMMYYYY','fecha actual formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_DDMMYYYYHHMM','fecha actual formato DD/MM/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_MM.DD.YYYY','fecha actual formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_MM.DD.YYYYHHMM','fecha actual formato MM.DD.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_MMDDYYYY','fecha actual formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_act_MMDDYYYYHHMM','fecha actual formato MM/DD/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_MM.DD.YYYYHHMM','Fecha efectiva de renovación en formato MM.DD.YYYYHHMM','14');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_MMDDYYYYHHMM','Fecha efectiva de renovación en formato MMDDYYYYHHMM','12');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_DD.MM.YYYY','Fecha de inicio de renovación en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_DD.MM.YYYYHHMM','Fecha de inicio de renovación en formato DD.MM.YYYYHHMM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_DDMMYYYY','Fecha de inicio de renovación en formato DDMMYYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_DDMMYYYYHHMM','Fecha de inicio de renovación en formato DDMMYYYYHHMM','12');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_MM.DD.YYYY','Fecha de inicio de renovación en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_MM.DD.YYYYHHMM','Fecha de inicio de renovación en formato MM.DD.YYYYHHMM','14');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_MMDDYYYY','Fecha de inicio de renovación en formato MMDDYYYY','8');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_ini_renov_MMDDYYYYHHMM','Fecha de inicio de renovación en formato MMDDYYYYHHMM','12');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_DDMMYYYY','fecha instalacion en formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_DDMMYYYYHHMM','fecha instalacion en formato DD/MM/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_MMDDYYYY','fecha instalacion en formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_comp','Importe que se ha compensado de la recarga SOS','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_comp_cp','Importe que se ha compensado mas penalización de la recarga SOS','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_comp_cp_eur','Importe que se ha compensado mas penalización de la recarga SOS','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_comp_eur','Importe que se ha compensado de la recarga SOS','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_coste','Importe del coste de la operación','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_coste_eur','Importe del coste de la operación en euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_pen_comp','Importe pendiente de compensar','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_pen_comp_cp','Importe pendiente de compensar más importe penalización pendiente de cobrar de la recarga SOS','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_pen_comp_cp_eur','Importe pendiente de compensar más importe penalización pendiente de cobrar de la recarga SOS','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_pen_comp_eur','Importe pendiente de compensar','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'num_sesiones_renov','Numero maximo de sesiones en las que se podra hacer uso el bono renovable','5');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'perio_sin_penal_hh','Periodo de tiempo en horas sin penalizar de la recargas SOS','4');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo','Saldo del abonado','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_caducado','Saldo caducado','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_eur','Saldo del abonado en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'umb_consum_eur','Umbral de consumo en euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_MMDDYYYYHHMM','fecha instalacion en formato MM/DD/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_DD.MM.YYYY','fecha instalacion en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_MM.DD.YYYY','fecha instalacion en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_DD.MM.YYYYHHMM','fecha instalacion en formato DD.MM.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_inst_MM.DD.YYYYHHMM','fecha instalacion en formato MM.DD.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bono_DDMMYYYY','Fecha de caducidad del bono con formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bono_MMDDYYYY','Fecha de caducidad del bono con formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bono_DD.MM.YYYY','Fecha de caducidad del bono con formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bono_MM.DD.YYYY','Fecha de caducidad del bono con formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'can_bonif','Cantidad bonificada','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'can_bonif2','Segunda Cantidad bonificada','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'num_sesiones','Numero maximo de sesiones en las que se podra hacer uso el bono','5');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'num_veces','Numero maximo de veces que puede contratarse el bono','3');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_ajus_eur','Importe del ajuste en euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_ajus','Importe del ajuste','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'cod_bolsa_ajus','Código de bolsa de saldo de la actuacion','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_bolsa_ajus','Descripción de la bolsa de saldo de la operación de ajuste','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_causa_ajus','Descripcion de la causa de ajuste de la actuacion','100');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'cod_tribu','código de tribu','4');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_tribu','Descripcion de la tribu','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'cod_lista','código de lista','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_lista','Descripción de la lista','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'item_nuevo','Nuevo item añadido a la lista','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'item_viejo','Item dado de baja de la lista ','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'items_news','Lista de nuevos items','70');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'plan_ant','Tipo de prepago anterior','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'plan_nuevo','Tipo de prepago nuevo','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_plan_ant','Descripción del tipo de prepago anterior','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_plan_nuevo','Descripcion del tipo de prepago nuevo','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCP_DDMMYYYY','Fecha de caducidad del abonado en formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCP_MMDDYYYY','Fecha de caducidad del abonado en formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCP_DD.MM.YYYY','Fecha de caducidad del abonado en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCP_MM.DD.YYYY','Fecha de caducidad del abonado en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_recarga','Importe de la recarga','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_recarga_eur','Importe de la recarga en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'plan_abo','Tipo de prepago actual del abonado','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_plan_abo','Descripción del tipo de prepago actual del abonado','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboRC_DDMMYYYY','Fecha de caducidad del abonado en formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboRC_MMDDYYYY','Fecha de caducidad del abonado en formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboRC_DD.MM.YYYY','Fecha de caducidad del abonado en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboRC_MM.DD.YYYY','Fecha de caducidad del abonado en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'val_rec_dias','Periodo de validez de la recarga en días','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'val_abo_meses','Periodo de validez del abonado en meses','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'cod_bolsa_rec','Código de bolsa de la recarga efectuada','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_bolsa_rec','Descripción de la bolsa de la recarga efectuada','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa1','Saldo de la bolsa 1','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa1_eur','Saldo de la bolsa 1 en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa2','Saldo de la bolsa 2','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa2_eur','Saldo de la bolsa 2 en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa3','Saldo de la bolsa 3','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa3_eur','Saldo de la bolsa 3 en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa4','Saldo de la bolsa 4','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa4_eur','Saldo de la bolsa 4 en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa5','Saldo de la bolsa 5','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa5_eur','Saldo de la bolsa 5 en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa6','Saldo de la bolsa 6','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_bolsa6_eur','Saldo de la bolsa 6 en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa1_DDMMYYYY','Fecha de caducidad bolsa 1 formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa1_MMDDYYYY','Fecha de caducidad bolsa 1 formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa1_DD.MM.YYYY','Fecha de caducidad bolsa 1 formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa1_MM.DD.YYYY','Fecha de caducidad bolsa 1 formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa2_DDMMYYYY','Fecha de caducidad bolsa 2 formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa2_MMDDYYYY','Fecha de caducidad bolsa 2 formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa2_DD.MM.YYYY','Fecha de caducidad bolsa 2 formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa2_MM.DD.YYYY','Fecha de caducidad bolsa 2 formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa3_DDMMYYYY','Fecha de caducidad bolsa 3 formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa3_MMDDYYYY','Fecha de caducidad bolsa 3 formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa3_DD.MM.YYYY','Fecha de caducidad bolsa 3 formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa3_MM.DD.YYYY','Fecha de caducidad bolsa 3 formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa4_DDMMYYYY','Fecha de caducidad bolsa 4 formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa4_MMDDYYYY','Fecha de caducidad bolsa 4 formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa4_DD.MM.YYYY','Fecha de caducidad bolsa 4 formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa4_MM.DD.YYYY','Fecha de caducidad bolsa 4 formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa5_DDMMYYYY','Fecha de caducidad bolsa 5 formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa5_MMDDYYYY','Fecha de caducidad bolsa 5 formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa5_DD.MM.YYYY','Fecha de caducidad bolsa 5 formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa5_MM.DD.YYYY','Fecha de caducidad bolsa 5 formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa6_DDMMYYYY','Fecha de caducidad bolsa 6 formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa6_MMDDYYYY','Fecha de caducidad bolsa 6 formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa6_DD.MM.YYYY','Fecha de caducidad bolsa 6 formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsa6_MM.DD.YYYY','Fecha de caducidad bolsa 6 formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsaumb_DDMMYYYY','Fecha caducidad bolsa formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsaumb_MMDDYYYY','Fecha caducidad bolsa formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsaumb_DD.MM.YYYY','Fecha de caducidad bolsa formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_bolsaumb_MM.DD.YYYY','Fecha caducidad bolsa formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'des_bolsa_umbral','Descripción de la bolsa de la operacion de umbral/caducad bolsa','40');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'dias_cad_bolsa','Días que faltan para la caducidad de la bolsa','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'dias_cad_abo','Días que faltan para la caducidad del abonado','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboUE_DDMMYYYY','Fecha caducidad del abonado en formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboUE_MMDDYYYY','Fecha caducidad del abonado en formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboUE_DD.MM.YYYY','Fecha caducidad del abonado en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboUE_MM.DD.YYYY','Fecha caducidad del abonado en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_prox_DDMMYYYY','Fecha caducidad próximo estado del abonado en formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_prox_MMDDYYYY','Fecha caducidad próximo del abonado en formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_prox_DD.MM.YYYY','Fecha caducidad próximo del abonado en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_prox_MM.DD.YYYY','Fecha caducidad próximo del abonado en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCS_DDMMYYYY','Fecha de caducidad del abonado en formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCS_MMDDYYYY','Fecha de caducidad del abonado en formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCS_DD.MM.YYYY','Fecha de caducidad del abonado en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_cad_aboCS_MM.DD.YYYY','Fecha de caducidad del abonado en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_MMDDYYYY','Fecha efectiva de renovación en formato MMDDYYYY','8');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_MM.DD.YYYY','Fecha efectiva de renovación en formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_DDMMYYYYHHMM','Fecha efectiva de renovación en formato DDMMYYYYHHMM','12');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_DD.MM.YYYYHHMM','Fecha efectiva de renovación en formato DD.MM.YYYYHHMM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_DDMMYYYY','Fecha efectiva de renovación en formato DDMMYYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_efec_renov_DD.MM.YYYY','Fecha efectiva de renovación en formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'can_bonif2_renov','Segunda cantidad bonificada del bono renovable','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'can_bonif_renov','Cantidad bonificada del bono renovable','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MMDDYYYY2','Fecha instalación cambio de ciclo formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MM.DD.YYYY2','Fecha instalación cambio de ciclo formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MMDDYYYYHHMM2','Fecha instalación cambio de ciclo formato MM/DD/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MM.DD.YYYYHHMM2','Fecha instalación cambio de ciclo formato MM.DD.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MMDDYYYYHHMM','Fecha instalación cambio de ciclo formato MM/DD/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MM.DD.YYYYHHMM','Fecha instalación cambio de ciclo formato MM.DD.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MMDDYYYY','Fecha instalación cambio de ciclo formato MM/DD/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_MM.DD.YYYY','Fecha instalación cambio de ciclo formato MM.DD.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DDMMYYYY2','Fecha instalación cambio de ciclo formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DD.MM.YYYY2','Fecha instalación cambio de ciclo formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DDMMYYYYHHMM2','Fecha instalación cambio de ciclo formato DD/MM/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DD.MM.YYYYHHMM2','Fecha instalación cambio de ciclo formato DD.MM.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DDMMYYYYHHMM','Fecha instalación cambio de ciclo formato DD/MM/YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DD.MM.YYYYHHMM','Fecha instalación cambio de ciclo formato DD.MM.YYYY HH:MM','16');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DDMMYYYY','Fecha instalación cambio de ciclo formato DD/MM/YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'fec_instcbcl_DD.MM.YYYY','Fecha instalación cambio de ciclo formato DD.MM.YYYY','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'dia_ciclopos2','dia de ciclo al que cambia','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'dia_ciclopos','dia de ciclo al que cambia','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'dia_cicloant2','dia de ciclo anterior','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'dia_cicloant','dia de ciclo anterior','2');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'abo_nuevo','Nuevo numero de abonado','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'umb_consum','Umbral de consumo','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_consum','Importe de consumo','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'imp_consum_eur','Importe de consumo en euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_recuperado_eur','Saldo recuperado en Euros','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_recuperado','Saldo recuperado','10');
insert into mensapatrones(cwdocid,cod_patronmensa,des_patronmensa_en,max_size) values(CWDOCSEQ.NEXTVAL,'saldo_caducado_eur','Saldo caducado en Euros','10');
commit;