truncate table MessageTypology;
delete from MessageTypology;

Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'LQNTS','LQNTS_ACTIVACION');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'LQNTS','LQNTS_CONSUMO');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'LQNTS','LQNTS_DESACTIVACION');

Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'SALDOTRAS','CONSUMO_MONEDEROS');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'SALDOTRAS','SALDO_MONEDEROS');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'SALDOTRAS','CADUCIDAD_MONEDEROS');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'SALDOTRAS','SIN_SALDO_MONEDEROS');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'SALDOTRAS','SALDO_BONOS');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'SALDOTRAS','CADUCIDAD_BONOS');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'SALDOTRAS','SIN_SALDO_BONOS');

Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'LLAM_CAIDA','BONIF_LLAM_CAIDAS');

Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'HOME_ZONE','ACTIVACION_HZ');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'HOME_ZONE','ERROR_HZ');

Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'UMBRESTR','UMBRESTR_BONO');
Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'UMBRESTR','UMBRESTR_RECHAZO');

Insert into MessageTypology (CWDOCID,TYPOLOGY,SUBTYPOLOGY) values (CWDOCSEQ.NEXTVAL,'BARRINGSMS','BARRINGSMS');

commit;

   
   