delete from SUBOPERATIONSBYOPERATION;
truncate table SUBOPERATIONSBYOPERATION;
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'AM','For any Wallet Activation','1','Wallet');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'SR','For any Bag','1','Wallet');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'RC','For any Recharge Origin','1','TopUpOrigin');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'RA','For any Recharge Origin','1','TopUpOrigin');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'AB','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'BB','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'CB','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'PH','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'BP','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'UB','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'AK','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'RK','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'AQ','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'UG','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'XB','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'XS','For any Bolt-on','1','BoltOn');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'RB','For any Bolt-on','1','BoltOn');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'AY','For any Periodic Action','1','CyclicActionSpecification');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'BY','For any Periodic Action','1','CyclicActionSpecification');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'Z5','For any Periodic Action','1','CyclicActionSpecification');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'CP','For any Plan','1','TariffPlan');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'AO','For any Promotional Profile','1','PromotionalProfile');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'BO','For any Promotional Profile','1','PromotionalProfile');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'AT','For any Tribe','1','Tribe');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'BT','For any Tribe','1','Tribe');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'TE','For any Timer','1','SOSTopUpInvitationTimer');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'P1','For any loan account activation','1','AutomaticTopUpMode');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'P2','For any loan account modification','1','AutomaticTopUpMode');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'P3','For any loan to account deactivation','1','AutomaticTopUpMode');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'NF','For any list activation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'SF','For any list deactivation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'QF','For any list activation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'IF','For any list query','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'JF','For any list activation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'KF','For any list activation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'HF','For any list activation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'XF','For any list activation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'UF','For any list activation','1','List');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'EF','For any list activation','1','List');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'YC','For any charging mode','1','ChargingMode');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'CY','For any change to life cycle status','1','CALifeCycleStatus');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'SA','For any subscription','1','Operation');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'IR','For any invitation','1','SOSTopUpInvitation');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION) values (CWDOCSEQ.NEXTVAL,'IC','For any invitation','1','SOSTopUpInvitation');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'AJ','For any Adjust Cause','0','AdjustmentCauseSubOp','AdjustmentCode');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'ZA','For any Type of Activation','0','SubscriberCreationSubOp','SubscriberCreationCode');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'PA','For any Type of Activation','0','SubscriberCreationSubOp','SubscriberCreationCode');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'MI','For any Type of Activation','0','SubscriberCreationSubOp','SubscriberCreationCode');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'DI','For any Type of Activation','0','SubscriberCreationSubOp','SubscriberCreationCode');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'BJ','For any Drop Cause','0','SubscriberDeletionSubOp','SubscriberDeletionCode');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'EA','For any Drop Cause','0','SubscriberDeletionSubOp','SubscriberDeletionCode');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'CO','For any charging origin','0','ChargingSubOp','ChargingOrigin');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE) values (CWDOCSEQ.NEXTVAL,'US','For any Threshold Balance','0','BalanceThresholdSubOp','BalanceThresholdIndicator');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE,RELATIONS,COMPLEX) values (CWDOCSEQ.NEXTVAL,'UC','For any Consum Balance','0','UCThresholdSubOp','ThresholdValue','UsageControl:UsageControlSpecification:UsageControlThresholdSetSpecific:UCThSetSpecifArr:List:UsageThresholdAmount','1');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE,RELATIONS,COMPLEX) values (CWDOCSEQ.NEXTVAL,'UL','For any Wallet/Threshold','0','WalletThresholdSubOp','WalletThresholdIndicator','Wallet:WWBalanceWarningThresArr:List:BalanceWarningThreshold','1');

Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE,RELATIONS,COMPLEX) values (CWDOCSEQ.NEXTVAL,'Z3','For any Cyclic Action/Timing','0','CycleSubOp','CyclicActionSpecification:TemporIntTime:TemporCodTime','MessageWarningRenewCA:CyclicActionSpecification:WRIntTemp:WRCodTemp','2');
Insert into SUBOPERATIONSBYOPERATION (CWDOCID,OPERATION,LABEL,ENTITY,SUBOPERATION,SUBOPERATIONCODE,RELATIONS,COMPLEX) values (CWDOCSEQ.NEXTVAL,'Z4','For any Cyclic Action/Timing','0','CycleSubOp','CyclicActionSpecification:TemporIntTime:TemporCodTime','MessageWarningExpirationCA:CyclicActionSpecification:WEIntTemp:WECodTemp','2');

commit;

